AreaDemo/Areas/Department/Models/Location.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AreaDemo.Areas.Departments.Models
{
    public class Location
    {
        public int ID { get; set; }

        public string Address { get; set; }

        public string City { get; set; }
    }
}

AreaDemo/Areas/Employee/Models/Employee.cs
using AreaDemo.Areas.Departments.Models;
using System.Data;

namespace AreaDemo.Areas.Employee.Models
{
    public class Employee
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public int LocationID { get; set; }
    }
}

AreaDemo/Models/ErrorViewModel.cs
using System;

namespace AreaDemo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AreaDemo/Areas/Department/Controllers/SalesController.cs
using AreaDemo.Areas.Departments.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AreaDemo.Areas.Departments.Controllers
{
    [Area("Department")]
    public class SalesController : Controller
    {
        public IActionResult Index()
        {
            Location[] salesLocation = new Location[] {
                new Location 
                { 
                    ID = 1, 
                    Address = "A Road",
                    City = "Pune"                    
                },
                new Location
                {
                    ID = 2,
                    Address = "B Road",
                    City = "London"
                },
                new Location
                {
                    ID = 3,
                    Address = "K Road",
                    City = "New York"
                },
            };
            return View(salesLocation);
        }
    }
}

AreaDemo/Areas/Employee/Controllers/SalesEmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AreaDemo.Areas.Employee.Controllers
{
    [Area("Employee")]
    public class SalesEmployeeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        
        public IActionResult GetEmployeeListByLocation(int locationID)
        {
           Models.Employee[] employees = new Models.Employee[] {
                new Models.Employee
                {
                    ID = 1,
                    Name = "Robert",
                    Designation="Manager",
                    LocationID=1
                },
                new Models.Employee
                {
                    ID = 2,
                    Name = "Steve",
                    Designation="Developer",
                    LocationID=1
                },
                new Models.Employee
                {
                    ID = 3,
                    Name = "Rajan",
                    Designation="CEO",
                    LocationID=2
                },
            };
            Models.Employee[] empList = 
                employees.Where(item => item.LocationID == locationID).ToArray();
            return View(empList);
        }
    }
}

AreaDemo/Controllers/HomeController.cs
using AreaDemo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AreaDemo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AreaDemo/Areas/Department/Views/Sales/Index.cshtml
@model IEnumerable<AreaDemo.Areas.Departments.Models.Location>

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers

@{
    Layout = "~/Views/Shared/_layout.cshtml";
}

<div class="table-responsive">
    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>Address</th>
                <th>City</th>
                <th>Employee List</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var p in Model)
            {
                <tr>
                    <td>@p.ID</td>
                    <td>@p.Address</td>
                    <td>@p.City</td>
                    <td>
                        <a asp-area="Employee" asp-controller="SalesEmployee"
                           asp-action="GetEmployeeListByLocation" 
                           asp-route-locationID =@p.ID>
                            View Employee List
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

AreaDemo/Areas/Employee/Views/SalesEmployee/GetEmployeeListByLocation.cshtml
@model IEnumerable<AreaDemo.Areas.Employee.Models.Employee>
@{
    Layout = "~/Views/Shared/_layout.cshtml";
}

<div class="table-responsive">
    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Designation</th>
                <th>LocationID</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var p in Model)
            {
                <tr>
                    <td>@p.ID</td>
                    <td>@p.Name</td>
                    <td>@p.Designation</td>
                    <td>@p.LocationID</td>
                </tr>
            }
        </tbody>
    </table>
</div>

AreaDemo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AreaDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AreaDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AreaDemo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AreaDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>